theme:  jekyll-theme-merlot
title: My Portfolio
name: Aristide
bio: Student at Lycée Guillaume Kroll(Brevet Technicien Superieur en Cloud Computing) 
--Cybersecurity Enthusiast | Aspiring Ethical Hacker | Protecting Data & Systems
social:
  twitter:
  linkedin: https://www.linkedin.com/in/aristide-katagaruka-b6a7a01aa/
